### ISSUE TITLE
Misclassified images

### ISSUE THREAD

**Issue by CristhianBoujon** [emanhamed/Houses-dataset#2]
Hello!
Due to my deep learning model trained with a extension of this dataset, I found some missclassified images:

- File 529_frontal.jpg is not a front of house... It is a kitchen
- File 466_kitchen.jpg is not a kitchen... it is a bathroom
- File 343_kitchen.jpg is not a kitchen... it is a bathroom
- File 221_bathroom.jpg is not a bathroom... it is a bedroom
- File 227_bedroom.jpg is not a bedroom... it is a kitchen
- File 12_bedroom.jpg is not a bedroom... it is a bathroom

Regards!

**Comment by emanhamed** [comment]
Thanks for your note. Will take care of that.
